# This is the Makefile for game-engine repository.

ci_docker_image_name = time-track-ci-autogenerated
pwd = $(PWD)

## ----------------------------------------------------------------------------
help: ## Show this help.
## ----------------------------------------------------------------------------
	@sed -ne '/@sed/!s/## //p' $(MAKEFILE_LIST)


## # HelloWorld.
## ----------------------------------------------------------------------------
build_hello_world: ## Build hello world application using bazel.
	bazel build //sandbox/bazel-example:hello_world

run_hello_world: ##   Run hello world application that was builded by bazel.
	./bazel-bin/sandbox/bazel-example/hello_world

